Repository pantheon-systems/documentation, pull requests merged in 2018-08, with the labels that each got.

#3918 Clarify that WordPress and WooCommerce core do not use PHP Sessions
  source/_docs/guides/woocommerce/03-configure.md
  source/_docs/wordpress-sessions.md
Labels: fix content

#3915 Removed outdated/broken Drupal LDAP help links.
  source/_docs/ldap-and-ldaps.md
Labels: CSE

#3877 Update gandi.md
  source/_docs/dns-providers/gandi.md
Labels: needs-more-info

#3927 Add example how to empty folders using rsync
  source/_docs/rsync-and-sftp.md
Labels: CSE, copy review

#3908 Add Force Login to the list
  source/_docs/modules-plugins-known-issues.md
Labels: CSE, in progress

#3944 update MSSQL library status
  source/_docs/modules-plugins-known-issues.md
Labels: new content

#3943 Add another step to removing automation
  source/_docs/guides/drupal-8-composer-no-ci.md
Labels: External, fix content

#3940 Added the snippet location in the wp-config
  source/_partials/redirects.twig
Labels: CSE, copy review

#3948 Update Comparison Table: Legacy Professional plan didn't include multidev
  source/_docs/new-plans-faq.md
Labels: CSE

#3951 Document setting custom upstream on existing site.
  source/_docs/create-custom-upstream.md
Labels: technical review

#3955 Uploading files over 256MB is not possible
  source/_docs/platform-considerations.md
Labels: CSE

#3964 Add Professional Services Note
  source/_docs/load-and-performance-testing.md
Labels: new content

#3965 add confirmation screenshot
  source/_docs/custom-certificates.md
  source/docs/assets/images/dashboard/custom-cert-confirm.png
Labels: new content

#3963 Update modules-plugins-known-issues.md
  source/_docs/modules-plugins-known-issues.md
Labels: CSE

#3966 Finding Site Name
  source/_docs/terminus/examples.md
Labels: technical review

#3972 Wp-CFM Note
  source/_docs/wp-cfm.md
Labels: copy review

#3977 update new issue URL encoding
  source/_views/doc.html
  source/_views/guide.html
Labels: site

#3979 Use valid syntax for example variables.
  source/_docs/cookies.md
Labels: CSE

#3985 Add ToC to WP Site Network guide intro.
  source/_docs/guides/multisite/01-introduction.md
Labels: copy review

#3971 Organization Permissions Update
  source/_docs/change-management.md
Labels: fix content

#3960 include quicksilver resolution to multiple DB find/replace
  source/_docs/database-workflow.md
Labels: technical review

#3986 Answer site name uniqueness
  source/_docs/create-sites.md
Labels: copy review, new content

#3996 Fixed a typo in drupal-cron.md
  source/_docs/drupal-cron.md
Labels: External

#3984 GitLab Custom Upstream
  source/_docs/create-custom-upstream.md
  source/docs/assets/images/dashboard/create-upstream-auth-bb.png
  source/docs/assets/images/dashboard/create-upstream-auth-gh.png
  source/docs/assets/images/gitlab-reporter.png
Labels: copy review, product

#3992 New Relic troubleshooting with private browser session
  source/_docs/new-relic.md
Labels: technical review

#4010 Update D8 no Composer guide to add a missing step
  source/_docs/guides/drupal-8-composer-no-ci.md
Labels: fix content, pantheor

#4015 Drush versions: Note that Drush 8 works for Drupal 6-8.
  source/_docs/drush-versions.md
Labels: CSE

#4016 Pantheon workflow: Fix Drupal file path.
  source/_docs/pantheon-workflow.md
Labels: CSE, in progress

#4011 Issue 4008 incorrect screenshot
  source/_docs/guides/drupal-8-composer-no-ci.md
  source/docs/assets/images/guides/drupal-8-composer-no-ci/drops-8-composer-git-status-after-installing-d8-and-removing-ci-components.png
  source/docs/assets/images/guides/drupal-8-composer-no-ci/drops-8-composer-git-status-after-installing-d8.png
  source/docs/assets/images/guides/drupal-8-composer-no-ci/drops-8-composer-install.png
  source/docs/assets/images/guides/drupal-8-composer-no-ci/drops-8-composer-update.png
  source/docs/assets/images/guides/drupal-8-composer-no-ci/drops-8-git-status-after-composer-update.png
Labels: fix content, pantheor

#3989 Solr Updates
  source/_docs/faq.md
  source/_docs/solr-drupal-7.md
  source/_docs/solr-drupal-8.md
  source/_docs/solr.md
  source/_docs/wordpress-solr.md
  source/_partials/content/solr-commit-changes.html
  source/_partials/content/solr-version.html
Labels: in progress

#4019 Continuation of #4011
  source/_docs/guides/drupal-8-composer-no-ci.md
Labels: copy review, fix content

#4025 add ssh auth references to Terminus installation
  source/_docs/terminus/install.md
Labels: new content

#4031 Updating #POPs Fastly Supports
  source/_docs/global-cdn.md
Labels: pantheor

#4023 note variable for Cloudflare
  source/_docs/client-ip.md
Labels: new content

#4022 note simultaneous connection error
  source/_docs/files.md
Labels: new content

#4033 Configure default cases for Multidev indicators
  source/_docs/environment-indicator.md
Labels: pantheor, technical review

#4034 multiple connections update
  source/_docs/pantheon-enterprise-gateway.md
Labels: copy review

#4036 Clarified language
  source/_docs/guides/build-tools/05-extend.md
Labels: copy review

#4035 Update change management for UIC
  source/_docs/change-management.md
Labels: new content

#3954 Add note S3 Uploads compatibility in Multisite
  source/_docs/wordpress-s3.md
Labels: blocked

#4038 Edit change-management.md
  source/_docs/change-management.md
Labels: CSE
