Repository pantheon-systems/documentation, pull requests merged in 2018-06, with the labels that each got.

#3726 List filemount last
  source/_docs/pantheon-yml.md
Labels: pantheor

#3731 Minor copy edits.
  source/_docs/tmp.md
Labels: CSE

#3733 Update number of app servers provisioned on a Test env
  source/_docs/faq.md
Labels: CSE

#3676 Enterprise Site Plans
  source/_docs/site-plan.md
Labels: hold for release, product

#3738 Add WP path to "Varnish, Public Files, and Cookies"
  source/_docs/caching-advanced-topics.md
Labels: CSE

#3748 Update FAQ to ref app containers not appservers
  source/_changelogs/2015-01-01-January.md
  source/_docs/caching-advanced-topics.md
  source/_docs/cloud-optimization.md
  source/_docs/debug-slow-performance.md
  source/_docs/external-libraries.md
  source/_docs/faq.md
  source/_docs/files.md
  source/_docs/git.md
  source/_docs/global-cdn-caching.md
  source/_docs/guides/launch/06-launch-check.md
  source/_docs/ldap-and-ldaps.md
  source/_docs/logs.md
  source/_docs/modules-plugins-known-issues.md
  source/_docs/new-relic.md
  source/_docs/organization-faq.md
  source/_docs/outgoing-ips.md
  source/_docs/pantheon-workflow.md
  source/_docs/pantheon_stripped.md
  source/_docs/php-errors.md
  source/_docs/sftp.md
  source/_docs/sso.md
  source/_docs/videos/cache.md
Labels: pantheor

#3757 Link to PHP version requirements from CMS docs
  source/_docs/php-versions.md
Labels: copy review

#3760 PEG qualifying blurb
  source/_docs/outgoing-ips.md
Labels: CSE

#3762 Update Solr info on FAQ
  source/_docs/faq.md
Labels: CSE

#3758 Update pantheon_stripped regex
  source/_docs/pantheon_stripped.md
Labels: copy review

#3763 Update external Git repo info in the FAQ
  source/_docs/faq.md
Labels: CSE

#3770 SEO tools addition clarification.
  source/_docs/bots-and-indexing.md
Labels: copy review

#3728 May/June Changelog
  source/_changelogs/2018-05-01-May.md
  source/_partials/changelog_preview.twig
Labels: hold for release

#3753 New DNS doc
  source/_docs/dns.md
  source/_docs/domains.md
  source/docs/assets/images/dashboard/dns-values.png
  source/docs/assets/images/dashboard/domain-added.png
  source/docs/assets/images/dashboard/domains-add-new.png
Labels: new doc, technical review

#3795 S3 Command Paths
  source/_docs/drupal-s3.md
Labels: technical review

#3813 Quickstart Update
  source/_docs/guides/quickstart/07-connection-modes.md
Labels: copy review

#3812 Update "Fast 404" on Known Issues list.
  source/_docs/modules-plugins-known-issues.md
Labels: CSE, copy review

#3739 Update session cookie info for Drupal 8
  source/_docs/caching-advanced-topics.md
Labels: CSE

#3772 Readability updates
  source/_docs/guides/drupal-8-composer-no-ci.md
Labels: fix content, from-feedback

#3811 Add All-in-One WP Migration to the known issues list.
  source/_docs/modules-plugins-known-issues.md
Labels: CSE

#3803 Custom Certificate Doc
  source/_docs/custom-certificates.md
Labels: new doc, pantheor

#3780 Update errors-and-server-responses.md
  source/_docs/errors-and-server-responses.md
Labels: CSE, copy review

#3791 Add info on what scopes the GitHub token needs
  source/_docs/guides/build-tools/01-introduction.md
Labels: External

#3793 Git migrate code
  source/_docs/migrate-manual.md
Labels: CSE

#3828 Clarify NR loss date
  source/_docs/new-plans-faq.md
Labels: fix content

#3829 Update force secure checkout screenshot
  source/_docs/guides/woocommerce/03-configure.md
  source/docs/assets/images/guides/woocommerce/12-force-secure-checkout.png
Labels: copy review, fix content

#3827 Add newly allowed bots
  source/_docs/bots-and-indexing.md
Labels: new content

#3809 Style Guide Update for Exports
  source/_docs/backups.md
  source/_docs/clear-caches.md
  source/_docs/cms-admin.md
  source/_docs/core-updates.md
  source/_docs/database-workflow.md
  source/_docs/debug-connections.md
  source/_docs/domains.md
  source/_docs/drupal-8-configuration-management.md
  source/_docs/style-guide.md
  source/_docs/tmp.md
  source/docs/assets/css/main.css
Labels: in progress

#3834 Add troubleshooting section to "Lock Environments"
  source/_docs/security.md
Labels: CSE, technical review

#3833 Note that PHP point releases cannot be specified in pantheon.yml
  source/_docs/php-versions.md
Labels: CSE
