Repository pantheon-systems/documentation, pull requests merged in 2018-12, with the labels that each got.

#4290 Link to TOS section
  source/_docs/site-plan.md
Labels: copy review

#4285 Pantheon.yml & Multidev & You
  source/_docs/php-versions.md
Labels: copy review, new content

#4284 Update php-versions.md
  source/_docs/php-versions.md
Labels: External, new content

#4272 Update private-paths.md
  source/_docs/private-paths.md
Labels: CSE, copy review, fix content

#4271 add CORS resolution in WP
  source/_docs/platform-considerations.md
Labels: copy review

#4291 Clarify Unprivileged User Access to Multidev
  source/_docs/multidev.md
Labels: copy review

#4293 Warn against creating non-empty repo
  source/_docs/create-custom-upstream.md
  source/docs/assets/images/github-create-readme.png
Labels: copy review

#4225 Incorrect robots.txt output in WordPress
  source/_docs/bots-and-indexing.md
Labels: copy review

#4281 Specify need for settings.php
  source/_docs/guides/terminus-drupal-site-management.md
Labels: copy review, new content

#4299 Clarify https requirements and provisioning
  source/_docs/guides/launch/04-configure-dns.md
  source/_partials/content/https-requirements.html
Labels: CSE, copy review, fix content

#4296 Invite-to-pay Clarifications
  source/_docs/site-billing.md
  source/_docs/site-plan.md
  source/_partials/content/transfer-ownership-billing-steps.html
Labels: copy review, fix content

#4303 Copy DNS provider drop-down
  source/_docs/domains.md
Labels: copy review

#4306 Update pantheon-enterprise-gateway.md
  source/_docs/ldap-and-ldaps.md
  source/_docs/pantheon-enterprise-gateway.md
Labels: PS, copy review

#4304 Leave the challenge file
  source/_docs/guides/launch/03-domains.md
Labels: copy review

#4301 Clarify IPv6 Compatibility
  source/_docs/dns-providers/network-solutions.md
Labels: copy review

#4295 Pantheon Solr Module with External Service
  source/_docs/solr-drupal-7.md
Labels: copy review

#4307 clarify multidev access on site level
  source/_docs/change-management.md
  source/_docs/multidev.md
Labels: copy review

#4230 Site Disaster Recovery
  source/_docs/disaster-recovery.md
  source/docs/assets/images/site-dr-diagram.png
Labels: copy review, new doc, pantheor

#4314 replace HTML with Markdown in note / warning callouts
  source/_docs/style-guide.md
Labels: copy review

#4317 add a client to an agency and send a bill
  source/_docs/add-bill-client.md
  source/_docs/organization-dashboard.md
  source/_docs/site-owner-faq.md
  source/_docs/team-management.md
  source/_partials/content/add-supporting-org.html
  source/_partials/content/invite-to-pay.html
  source/_partials/content/transfer-ownership-billing-steps.html
  source/docs/assets/images/dashboard/multi_org1.png
Labels: in progress, new doc

#4313 note proper ownership transfer method
  source/_docs/agency-tips.md
Labels: copy review

#4273 Add Composer install directions for SimpleSAMLphp
  source/_docs/shibboleth-sso.md
Labels: CSE, copy review

#4322 add clarity to the filemount path option
  source/_docs/pantheon-yml.md
Labels: copy review

#4321 Note the Terminus ACME plugin
  source/_docs/guides/launch/03-domains.md
Labels: copy review

#4325 Fix SimpleSAML Composer heading
  source/_docs/shibboleth-sso.md
Labels: CSE

#4327 Add Launch Check opt-out example for D8.
  source/_docs/drupal-launch-check.md
Labels: CSE, copy review

#4329 Faq headers
  source/_docs/settings-php.md
Labels: copy review

#4331 SSH Keys are good, mmmmkay?
  source/_docs/guides/drupal8-commandline.md
Labels: copy review

#4320 add note about scope of support
  source/_docs/guides/build-tools/01-introduction.md
Labels: copy review

#4335 Removing unused settings.php step in Drupal 8 command line guide
  source/_docs/guides/drupal8-commandline.md
Labels: copy review, fix content, pantheor

#4338 Safely Remove Redis
  source/_docs/disaster-recovery.md
  source/_partials/content/remove-addons/d7-redis.html
  source/_partials/content/remove-addons/d8-redis.html
  source/_partials/content/remove-addons/wp-redis.html
Labels: copy review, fix content, new content

#4333 Hold on to your keys
  source/_docs/guides/build-tools/02-create-project.md
Labels: copy review

#4332 Writable WP Debug Log Path
  source/_docs/wp-config-php.md
Labels: copy review

#4348 Also added wp for the large sites
  source/_docs/migrate-manual.md
Labels: copy review

#4343 Fix Solr schema post path for D7.
  source/_docs/solr-drupal-7.md
Labels: CSE, copy review

#4359 Note typical provision time
  source/_docs/relaunch.md
Labels: copy review
