Repository pantheon-systems/documentation, pull requests merged in 2018-10, with the labels that each got.

#4107 Update new-plans-faq.md
  source/_docs/new-plans-faq.md
Labels: External

#4110 Added issue/resolution to better search replace
  source/_docs/modules-plugins-known-issues.md
Labels: CSE, in progress, new content

#4121 wp-offload-s3 has been renamed wp-offload-media
  source/_docs/platform-considerations.md
  source/_docs/wordpress-s3.md
Labels: copy review, fix content, pantheor

#4124 traffic clarification
  source/_docs/metrics.md
Labels: CSE, copy review

#4128 Update pantheon-enterprise-gateway.md
  source/_docs/pantheon-enterprise-gateway.md
Labels: EOM, fix content

#4113 Rephrase Basic Auth within Caching: Advanced Topics
  source/_docs/caching-advanced-topics.md
Labels: CSM, copy review

#4133 Multidev faq addition
  source/_docs/multidev.md
Labels: copy review, new content

#4135 Increase discoverability for CSR info
  source/_docs/custom-certificates.md
Labels: CSM

#4108 Adding info on data export limitations
  source/_docs/platform-considerations.md
Labels: CSE, copy review, new content

#4139 Update client-ip.md
  source/_docs/client-ip.md
Labels: External

#4085 Update onelogin wp tfa instructions
  source/_docs/guides/two-factor-authentication.md
  source/docs/assets/images/tfa-onelogin-custom-actions.png
  source/docs/assets/images/tfa-onelogin-new-user.png
  source/docs/assets/images/tfa-onelogin-tfa-methods.png
  source/docs/assets/images/tfa-onelogin-wp-login.png
  source/docs/assets/images/tfa-wp-onelogin-config.png
  source/docs/assets/images/tfa-wp-onelogin-ident.png
  source/docs/assets/images/tfa-wp-onelogin-options.png
Labels: CSE, technical review

#4136 Start Upgrade button location details
  source/_docs/global-cdn.md
Labels: CSE, copy review

#4104 Add <site> to header in Terminus Examples doc
  source/_docs/terminus/examples.md
  source/docs/assets/images/terminus-example-cc.png
  source/docs/assets/images/terminus-examples-field-name.png
  source/docs/assets/js/jquery.tocify.js
Labels: CSM, technical review

#4150 Update message shown for a 504 Gateway Timeout
  source/_docs/errors-and-server-responses.md
Labels: CSE, technical review

#4144 Add Unyson page builder plugin in issues page
  source/_docs/modules-plugins-known-issues.md
Labels: CSE, copy review

#4134 Update client-ip.md - Domain Access & Cloudflare
  source/_docs/client-ip.md
Labels: copy review

#4086 Remove Symlink
  source/_docs/assuming-write-access.md
Labels: CSE

#4154 Updating Drupal 8 Solr information
  source/_docs/solr-drupal-8.md
Labels: copy review, pantheor

#4156 fix small typo
  source/_docs/guides/frontend-performance.md
Labels: External, fix content

#4071 Visual Composer and WPBakery Page Builder
  source/_docs/modules-plugins-known-issues.md
Labels: CSE, copy review

#4149 Update CDN testing info (using browsers)
  source/_docs/test-global-cdn-caching.md
Labels: CSE, copy review

#4120 Add FileZilla Quickconnect troubleshooting
  source/_docs/filezilla.md
Labels: CSE

#4159 Cancellation: No partial refund
  source/_docs/site-plan.md
Labels: copy review

#4161 Clarify which sections are Drupal-specific
  source/_docs/global-cdn-caching.md
Labels: CSE

#4138 Added coming soon wp plugin
  source/_docs/modules-plugins-known-issues.md
Labels: CSE, new content, technical review

#4070 add debug.log location override in wpconfig
  source/_docs/logs.md
  source/_docs/wp-config-php.md
Labels: copy review

#4118 Adding WP best practices
  source/_docs/wordpress-best-practices.md
Labels: CSE, copy review

#4164 D8 Composer WO CI - Style alignment updates.
  source/_docs/guides/drupal-8-composer-no-ci.md
  source/docs/assets/images/guides/drupal-8-composer-no-ci/drops-8-composer-git-status-after-installing-d8.png
  source/docs/assets/images/guides/drupal-8-composer-no-ci/drops-8-composer-update.png
Labels: copy review

#4097 Developing on Pantheon Directly with SFTP Mode Doc Update
  source/_docs/sftp.md
Labels: CSE, copy review

#4160 Tweaks to MD in logs
  source/_docs/logs.md
Labels: copy review

#4155 Update gitignore info
  source/_docs/code.md
  source/_docs/git-faq.md
Labels: CSE, copy review

#4168 Added managewp worker in known issues page
  source/_docs/cms-admin.md
  source/_docs/modules-plugins-known-issues.md
Labels: copy review, new content

#4169 Update-Dyn.md
  source/_docs/dns-providers/dyn.md
Labels: External, needs-more-info

#4189 Test Email as part of Launch Check
  source/_docs/guides/launch/02-plans.md
  source/_docs/guides/launch/06-launch-check.md
Labels: copy review, fix content, new content, product

#4197 align with pricing page
  source/_partials/content/tables/custom-domains-limit.html
Labels: CSM

#4180 add SmartCrawl Pro to plugin with issues
  source/_docs/modules-plugins-known-issues.md
Labels: CSE, copy review, new content

#4190 Add overflow to ToC CSS
  source/docs/assets/css/main.css
Labels: site, technical review

#4196 Fix Broken links
  app/config/sculpin_site.yml
  source/_docs/agency-tips.md
  source/_docs/dns-providers/route53.md
  source/_docs/guides/pagerduty/02-monitor.md
  source/_docs/guides/pivotal-tracker.md
  source/_docs/guides/two-factor-authentication.md
  source/_docs/solr-drupal-7.md
Labels: technical review

#4202 Copy Clarification re: large files
  source/_docs/platform-considerations.md
Labels: fix content

#4204 Fix tabs in custom upstream doc
  source/_docs/create-custom-upstream.md
Labels: CSM, copy review

#4203 Fixes initial failure on Write a New Test example
  source/_docs/guides/build-tools/06-tests.md
Labels: External, copy review, fix content

#4206 Adding cross reference to Cron for Drupal page
  source/_docs/faq.md
Labels: copy review

#4207 Adding mention of Synthetics' based cron triggering
  source/_docs/drupal-cron.md
Labels: copy review

#4209 Add WP All Import / Export to Known Issues doc
  source/_docs/modules-plugins-known-issues.md
Labels: new content, technical review

#4208 Update Sendgrid Instructions
  source/_docs/guides/sendgrid.md
  source/docs/assets/images/guides/sendgrid/sendgrid-api-keys.png
  source/docs/assets/images/guides/sendgrid/sendgrid-wpconfig.png
  source/docs/assets/images/sendgrid-multiple-users.png
  source/docs/assets/images/sendgrid_wpconfig.png
Labels: copy review, fix content

#4212 grammar fix
  source/_docs/terminus/install.md
Labels: External, fix content
