Repository pantheon-systems/documentation, pull requests merged in 2018-02, with the labels that each got.

#3283 More Leads to Agencies
  source/_docs/faq.md
  source/_docs/getting-support.md
  source/_partials/footer_content.html
Labels: hold for release

#3297 Troubleshooting update for issue #114
  source/_docs/guides/build-tools/02-create-project.md
Labels: pantheor

#3294 Adding a missing directory for Terminus Composer Plugin
  source/_docs/guides/build-tools/01-introduction.md
Labels: External

#3312 Update modules.md
  source/_docs/modules.md
Labels: External

#3313 Update plugins.md
  source/_docs/plugins.md
Labels: External

#3318 Pantheon Enterprise Gateway
  source/_docs/pantheon-enterprise-gateway.md
Labels: copy review, new content

#3331 Committing SFTP Changes
  source/_docs/sftp.md
  source/docs/assets/images/dashboard/pantheon-dashboard-uncommitted-changes.png
Labels: CSE

#3332 Update debug-slow-performance.md
  source/_docs/debug-slow-performance.md
Labels: CSE, fix content

#3339 Reinforce domain masking limitations.
  source/_docs/platform-considerations.md
Labels: CSE, team-alex

#3336 Update mysql-access.md
  source/_docs/mysql-access.md
Labels: CSE, team-alex

#3343 Single Source Authentication Content
  source/_docs/rsync-and-sftp.md
  source/_docs/sftp.md
  source/_partials/content/auth.html
Labels: CSE, team-rachel

#3327 Show how to run SQL queries for WordPress sites using Terminus and WP-CLI
  source/_docs/wp-cli.md
Labels: CSE, technical review

#3334 Don't specify D7 on Status Report
  source/_docs/drupal-launch-check.md
Labels: CSE, team-rachel

#3335 Reference Drupal Launch check
  source/_docs/guides/launch/07-next-steps.md
Labels: CSE, team-rachel

#3337 Update 01-introduction.md
  source/_docs/guides/launch/01-introduction.md
Labels: CSM, team-rachel

#3340 Troubleshooting information for SES sandbox mode
  source/_docs/email.md
Labels: team-rachel

#3338 Update drush.md
  source/_docs/drush.md
Labels: CSE, team-rachel

#3341 Improve Redis Note on Launch Essentials Dropdown
  source/_docs/guides/launch/06-launch-check.md
Labels: team-rachel

#3344 Update 06-launch-check.md
  source/_docs/guides/launch/06-launch-check.md
Labels: CSM, team-rachel

#3342 Add a step for adding an SSH key to your account.
  source/_docs/guides/build-tools/01-introduction.md
Labels: CSE, team-rachel

#3353 Add link to Quick Start guide.
  source/_docs/pantheon-workflow.md
Labels: CSE, team-rachel

#3352 Update solr.md
  source/_docs/solr.md
Labels: CSE, team-alex

#3347 Add tip to check PHP version before install.
  source/_docs/terminus/install.md
Labels: CSE, team-rachel

#3349 Update multidev.md
  source/_docs/multidev.md
Labels: CSE, team-rachel

#3351 Troubleshoot failed pulls from upstram
  source/_docs/migrate-manual.md
Labels: CSE, team-rachel

#3363 PHP Memory Limit = Application Memory Limit
  source/_docs/platform-resources.md
Labels: CSE, team-alex

#3381 Remove global_redirect
  source/_docs/modules-plugins-known-issues.md
Labels: CSE, team-alex

#3380 Correct loggingdir variable
  source/_docs/shibboleth-sso.md
Labels: CSE, team-alex

#3346 Update faq.md
  source/_docs/faq.md
Labels: CSE, team-alex

#3402 Update HR class for HTML 5
  source/docs/assets/css/main.css
Labels: site

#3400 copy edit
  source/_docs/pantheon-enterprise-gateway.md
Labels: CSM

#3348 Added Windows 10 troubelshooting
  source/_docs/terminus/install.md
Labels: CSE, team-alex

#3360 Add link to existing doc on switching domains
  source/_docs/domains.md
Labels: CSE, team-alex

#3425 Remove Fastly from FAQ entry
  source/_docs/https.md
Labels: fix content

#3382 Start State Scope
  source/_docs/start-state.md
Labels: CSE, team-alex

#3373 Memory Errors
  source/_docs/debug-slow-performance.md
Labels: CSE, team-alex

#3371 Front and End doc Links
  source/_docs/style-guide.md
Labels: copy review, team-alex

#3383 Fix Drupal docs link.
  source/_docs/guides/quickstart/08-onserver-dev-part1.md
Labels: CSE, team-rachel

#3362 No default label on new issues reported from contribute button
  source/_views/doc.html
  source/_views/guide.html
  source/_views/terminuspage.html
  source/_views/video.html
Labels: CSE, team-rachel

#3366 Warn users not to `git revert` upstream updates
  source/_docs/undo-commits.md
Labels: CSE, team-rachel

#3361 Users cannot set environment variables.
  source/_docs/read-environment-config.md
Labels: CSE, new content, team-rachel

#3367 Add copy about expanded IPv6 records.
  source/_docs/domains.md
Labels: CSE, team-rachel

#3368 Update global-cdn.md
  source/_docs/global-cdn.md
Labels: CSE, team-rachel
