Repository pantheon-systems/documentation, pull requests merged in 2018-04, with the labels that each got.

#3465 Consolidate Separate Results Page in Docs
  source/_partials/dash_search_box.html
  source/_partials/navbar.html
  source/_partials/new_dash_search_box.html
  source/docs/dash-search.html
  source/docs/search.html
Labels: hold for release

#3470 Update drupal-cron.md
  source/_docs/drupal-cron.md
Labels: copy review

#3375 Add section on expiring cache on static assets
  source/_docs/caching-advanced-topics.md
Labels: CSE, team-alex

#3404 Release schedule for core & security updates
  source/_docs/core-updates.md
Labels: CSE, new content, technical review

#3438 Added WordPress themes section with Jupiter theme
  source/_docs/modules-plugins-known-issues.md
Labels: CSE, new content

#3445 Add Missing Notes on Symlink
  source/_docs/assuming-write-access.md
Labels: CSE, copy review, fix content

#3493 remove unneeded configs
  source/_docs/redis.md
Labels: External, technical review

#3545 Update Build Tools multidev names.
  source/_docs/guides/build-tools/02-create-project.md
  source/_docs/guides/build-tools/03-new-pr.md
  source/_docs/guides/build-tools/05-extend.md
  source/docs/assets/images/pr-workflow/block-placements.png
  source/docs/assets/images/pr-workflow/commit-added.png
  source/docs/assets/images/pr-workflow/commit-export.png
  source/docs/assets/images/pr-workflow/configuration-synchronize-warning.png
  source/docs/assets/images/pr-workflow/modified-css.png
  source/docs/assets/images/pr-workflow/pr-slogan-site.png
  source/docs/assets/images/pr-workflow/slogan-pr-passed.png
  source/docs/assets/images/pr-workflow/slogan-pr-starting.png
  source/docs/assets/images/pr-workflow/visit-multidev.png
Labels: copy review

#3378 Guide for Pantheon Advanced Page Cache in Drupal 8
  source/_docs/guides/drupal-8-advanced-page-cache.md
  source/_docs/guides/frontend-performance.md
  source/docs/assets/images/guides/drupal-8-advanced-page-cache/img1-config-dev-performance.png
  source/docs/assets/images/guides/drupal-8-advanced-page-cache/img10-node-add-article2.png
  source/docs/assets/images/guides/drupal-8-advanced-page-cache/img11-view-taxonomy-term.png
  source/docs/assets/images/guides/drupal-8-advanced-page-cache/img12-page-caching-option.png
  source/docs/assets/images/guides/drupal-8-advanced-page-cache/img13-node-add-article-3.png
  source/docs/assets/images/guides/drupal-8-advanced-page-cache/img2-node-add-article.png
  source/docs/assets/images/guides/drupal-8-advanced-page-cache/img3-node-1-dev-console.png
  source/docs/assets/images/guides/drupal-8-advanced-page-cache/img4-node-1-dev-console.png
  source/docs/assets/images/guides/drupal-8-advanced-page-cache/img5-taxonomy-term-1.png
  source/docs/assets/images/guides/drupal-8-advanced-page-cache/img6-node-add-page-2.png
  source/docs/assets/images/guides/drupal-8-advanced-page-cache/img7-node-edit-admin.png
  source/docs/assets/images/guides/drupal-8-advanced-page-cache/img8-node-add-article.png
  source/docs/assets/images/guides/drupal-8-advanced-page-cache/img9-sftp-client.png
Labels: new doc, pantheor

#3542 add-incommon
  source/_docs/https.md
Labels: CSM

#3483 Drush ard and nested docroot
  source/_docs/migrate.md
Labels: CSE, copy review

#3554 Add watch.php
  watch.php
Labels: site

#3552 Metrics in the Live Environment
  source/_docs/global-cdn.md
  source/_docs/metrics.md
  source/_docs/new-plans-faq.md
  source/_docs/traffic-limits.md
Labels: hold for release, product

#3559 Remove outdated HSTS example.
  source/_docs/hsts.md
Labels: CSE, fix content

#3566 Update new-relic.md
  source/_docs/new-relic.md
Labels: External

#3572 March changelog
  source/_changelogs/2018-03-01-March.md
  source/_partials/changelog_preview.twig
  source/_partials/content/changelog-optin.html
Labels: copy review

#3573 request debug header
  source/_docs/test-global-cdn-caching.md
Labels: technical review

#3571 Correct target not responding error code to 504.
  source/_docs/errors-and-server-responses.md
Labels: CSE

#3532 Redirect from One Path or Multiple Paths
  source/_docs/domains.md
Labels: CSE, fix content, help wanted, technical review

#3540 Add reference to search-replace troubleshoot doc
  source/_docs/wp-cli.md
Labels: CSE

#3584 Remove outdated section from Redis FAQ
  source/_docs/redis.md
Labels: CSE

#3453 troubleshoot custom upstream checks
  source/_docs/core-updates.md
  source/docs/assets/images/dashboard/check-for-updates.png
Labels: new content, technical review

#3586 stronger intros
  source/_docs/domains.md
Labels: copy review

#3596 Add guidance to disable BigPipe.
  source/_docs/modules-plugins-known-issues.md
Labels: CSM

#3458 No need to export, build-tools will cache
  source/_docs/guides/build-tools/01-introduction.md
  source/_docs/guides/build-tools/02-create-project.md
Labels: copy review, pantheor

#3591 Relaunch Existing Pantheon Sites
  app/config/sculpin_site.yml
  source/_docs/domains.md
  source/_docs/drupal-updates.md
  source/_docs/relaunch.md
  source/_docs/switching-dns.md
  source/_partials/content/enable-https.html
  source/_partials/content/notes/https-info.html
  source/_partials/content/notes/https-success.html
  source/_partials/content/standard-dns-config.html
  source/_partials/content/standard-dns-config2.html
  source/_partials/ttl.twig
  source/_partials/ttl2.twig
  source/docs/assets/css/main.css
Labels: copy review, product

#3489 WordPress Incorrect foreach loop
  source/_docs/environment-specific-config.md
Labels: CSE, copy review

#3589 Assessing Alerts Partial File
  source/_docs/guides/pagerduty/02-monitor.md
  source/_docs/guides/pingdom-uptime-check.md
  source/_docs/new-relic.md
  source/_partials/content/monitor-alerts.html
Labels: copy review

#3609 Cancel Current Plan
  app/config/sculpin_site.yml
  source/_docs/relaunch.md
  source/_docs/site-owner-faq.md
  source/_docs/site-plan.md
  source/_partials/content/transfer-owernship-billing-intro.html
  source/_views/post.html
  source/docs/assets/css/main.css
  source/docs/assets/images/dashboard/cancel-plan.png
  source/docs/assets/images/dashboard/change-plan.png
  source/docs/assets/images/dashboard/confirm-cancellation.png
  source/docs/assets/images/dashboard/select-plan.png
  source/docs/assets/images/dashboard/upgrade-plan.png
Labels: copy review, product

#3592 FAQ table on HTTPS specs
  source/_docs/https.md
Labels: technical review

#3615 serialize doc and repeat for newest patches
  source/_docs/drupal-security-patches.md
Labels: technical review

#3623 Terminus Authentication: Create token
  source/_docs/terminus/install.md
Labels: CSE, copy review

#3611 new relic account holder and password reset
  source/_docs/new-relic.md
Labels: copy review

#3625 site plans update
  source/_docs/new-relic.md
Labels: CSM

#3622 Make the load testing steps CMS-agnostic
  source/_docs/load-and-performance-testing.md
Labels: CSE

#3620 Contain Images within Content Wells
  app/config/sculpin_site.yml
  source/docs/assets/css/main.css
  wraith.yaml
Labels: site

#3629 add clarifying language
  source/_docs/maintain-custom-upstream.md
Labels: copy review

#3630 explain lag in metrics
  source/_docs/metrics.md
Labels: CSM, copy review
