Repository pantheon-systems/documentation, pull requests merged in 2018-05, with the labels that each got.

#3638 Update alternative-php-cache.md
  source/_docs/alternative-php-cache.md
Labels: CSE, copy review

#3635 git mode required for restore
  source/_docs/restore-environment-backup.md
Labels: CSM, copy review

#3618 Update PR and Issue Templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: copy review

#3606 Update TLS section
  source/_changelogs/2017-06-01-June.md
  source/_docs/new-relic.md
Labels: copy review

#3643 Font Enhancements
  app/config/sculpin_site.yml
  source/_views/contrib.html
  source/_views/default.html
  source/docs/assets/css/main.css
Labels: hold for release, site

#3603 Can't pre-provision from WPEngine
  source/_docs/guides/launch/03-domains.md
  source/_docs/migrate.md
Labels: copy review, pantheor

#3555 Legacy vs New Plans Resource Comparison
  source/_docs/new-plans-faq.md
  source/_docs/platform-resources.md
Labels: copy review

#3671 Account for the submodules issue
  source/_docs/guides/partial-composer.md
Labels: in progress, new content

#3664 Improve readability of "Fix errors" section
  source/_docs/errors-and-server-responses.md
Labels: CSE

#3673 fixing broken markdown
  source/_docs/new-relic.md
Labels: pantheor

#3660 Added a bit about ENV value being case-sensitive
  source/_docs/rsync-and-sftp.md
Labels: CSE

#3672 Elaborate on Composer Install for Drupal 7
  source/_docs/guides/sendgrid.md
Labels: CSE, External, in progress, new content

#3649 Table prefixes
  source/_docs/wordpress-known-issues.md
Labels: CSE, copy review

#3654 Requirements list: Terminus
  source/_docs/maintain-custom-upstream.md
Labels: CSE, copy review

#3679 April-May changelog
  source/_changelogs/2018-04-01-April.md
  source/_partials/changelog_preview.twig
Labels: copy review

#3604 Update link to plan resources.
  source/_docs/debug-slow-performance.md
Labels: CSE, copy review

#3651 Update Manually Expiring Cache for Static Assets
  source/_docs/caching-advanced-topics.md
Labels: copy review, pantheor

#3682 Explicitly defining code style for the code blocks
  source/_docs/guides/wordpress-commandline.md
Labels: technical review

#3599 Update core-updates.md
  source/_docs/core-updates.md
Labels: External

#3698 Note that hotfixes don't reload pantheon.yml.
  source/_docs/pantheon-yml.md
Labels: CSE

#3683 Fix Drush "aa" command example
  source/_docs/drupal-launch-check.md
Labels: CSE, technical review

#3701 List the Terminus site clone plugin under 'How do I clone an existing Pantheon site?'
  source/_docs/migrate.md
Labels: pantheor, technical review

#3702 updates for new plans
  source/_docs/support.md
Labels: copy review

#3703 WIP Professional Services
  source/_docs/professional-services.md
Labels: in progress

#3707 Reset password clarification
  source/_docs/resetting-passwords.md
Labels: CSE

#3705 Update create-custom-upstream.md
  source/_docs/create-custom-upstream.md
Labels: CSE

#3697 Add troubleshooting suggestions for infinite redirect loops
  source/_docs/domains.md
Labels: CSE, technical review

#3712 update copy for site auditor
  source/_docs/bots-and-indexing.md
Labels: copy review

#3708 Add documentation for 'filemount' in pantheon.yml
  source/_docs/pantheon-yml.md
Labels: copy review

#3689 Temporary File Management Refactor
  source/_changelogs/2016-03-01-March.md
  source/_docs/horizontal-scalability.md
  source/_docs/modules-plugins-known-issues.md
  source/_docs/temp-files.md
  source/_docs/tmp.md
  source/docs/assets/images/d7-vget-tmp-default.png
  source/docs/assets/images/d7-vget-tmp-filesystem.png
  source/docs/assets/images/d8-cget-tmp-default.png
  source/docs/assets/images/d8-cget-tmp-filesystem.png
  source/docs/assets/images/wp-config-get-tmp-default.png
  source/docs/assets/images/wp-config-get-tmp-filesystem.png
Labels: technical review
