Repository pantheon-systems/documentation, pull requests merged in 2018-03, with the labels that each got.

#3370 Further explanation of resolution of broken one-click updates.
  source/_docs/upstream-updates.md
Labels: CSE, team-rachel

#3374 Add standards for documenting error messages
  source/_docs/style-guide.md
Labels: team-rachel

#3372 Add a note about updating auth tokens.
  source/_docs/guides/build-tools/02-create-project.md
Labels: CSE, team-rachel

#3377 Fix up multidev doc
  source/_docs/multidev.md
Labels: team-rachel

#3386 Fix initial Git tag name.
  source/_docs/git-faq.md
Labels: CSE, team-rachel

#3387 Update Git version.
  source/_docs/git-faq.md
Labels: CSE, team-rachel

#3388 Clear cache doesn't include Redis
  source/_docs/clear-caches.md
Labels: CSE, team-alex

#3384 Scope for Public Distributions
  source/_docs/getting-support.md
Labels: CSE, team-alex

#3420 Clarify New Relic location in Dashboard
  source/_docs/site-owner-faq.md
Labels: copy review

#3410 Multi page cache control
  source/_docs/cache-control.md
Labels: CSE, fix content, technical review

#3430 Upcoming price increase for legacy SSL
  source/_docs/global-cdn.md
Labels: fix content

#3461 Update drush.md
  source/_docs/drush.md
Labels: CSM

#3407 PHP-FPM Missing words/content
  source/_docs/application-containers.md
Labels: CSE, technical review

#3424 Remove third-party CDN note from AWS page.
  source/_docs/drupal-s3.md
Labels: CSE, technical review

#3436 Fix syntax error in setcookie() example.
  source/_docs/cookies.md
Labels: CSE, technical review

#3452 Fix sentence structure for "write access" description
  source/_docs/platform-considerations.md
Labels: CSE, fix content

#3450 Update logformat from "%h,%^" to ~h{," }
  source/_docs/nginx-access-log.md
Labels: CSE, fix content

#3456 Replace Docs Search Service
  source/_partials/navbar.html
  source/_partials/new_dash_search_box.html
  source/_partials/search_box.html
  source/docs/search.html
Labels: hold for release

#3457 Markdown Tables
  app/config/sculpin_site.yml
  source/_docs/php-errors.md
  source/_docs/redis.md
  source/_docs/solr.md
  source/_docs/style-guide.md
  source/docs/assets/css/main.css
Labels: new content, site

#3467 Remove Dependencies Added Upstream
  source/_docs/guides/drupal-8-commerce.md
Labels: fix content

#3460 New section `Disable Caching on Development environment`
  source/_docs/cookies.md
Labels: CSE, copy review, new content

#3463 Add additional code snippet to domains.md
  source/_docs/domains.md
  source/_docs/http-to-https.md
  source/_docs/https.md
Labels: CSE, copy review, help wanted

#3476 Update 05-redirects.md
  source/_docs/guides/launch/05-redirects.md
Labels: CSE, new content

#3471 Update ImageMagick version.
  source/_docs/external-libraries.md
Labels: CSE

#3474 Clarify creating and calling settings.local.php
  source/_docs/local-development.md
Labels: CSE

#3369 Remove Kalabox Doc.
  source/_docs/agency-tips.md
  source/_docs/guides/quickstart/10-next-steps.md
  source/_docs/kalabox.md
  source/_docs/local-development.md
  source/_docs/php-versions.md
  source/_docs/videos/drush.md
  source/_docs/videos/kalabox.md
  source/_docs/videos/local.md
  source/_docs/videos/wp-cli.md
  source/_partials/content/deprecate-kalabox.html
Labels: CSE, team-rachel

#3479 Edit description
  source/_docs/undo-commits.md
Labels: EOM

#3412 Expand SFTP move limitation
  source/_docs/sftp.md
Labels: CSE, technical review

#3434 Switch CircleCI config from 1.0 to 2.0.
  .circleci/config.yml
  circle.yml
  scripts/deploy-multidev.sh
  scripts/run-sitespeed-test.sh
Labels: in progress

#3491 nr-reset
  source/_docs/new-relic.md
Labels: CSM

#3478 updating info on error reporting on dash
  source/_docs/sites.md
Labels: EOM

#3497 New User Account and Site Billing Docs
  source/_docs/account-billing.md
  source/_docs/change-management.md
  source/_docs/delete-account.md
  source/_docs/guides/launch/02-plans.md
  source/_docs/site-access.md
  source/_docs/site-billing.md
  source/_docs/site-owner-faq.md
  source/_docs/site-payments.md
  source/_docs/update-payment-method.md
  source/_docs/user-dashboard.md
  source/_partials/content/transfer-owernship-billing.html
  source/docs/assets/images/dashboard/billing_update.jpg
  source/docs/assets/images/dashboard/site-billing-cc-added.png
  source/docs/assets/images/dashboard/site-billing-cc-removed.png
  source/docs/assets/images/dashboard/site-billing-cc-updated.png
Labels: hold for release, product

#3503 Pantheon 4 trainers
  source/_docs/guides/trainers.md
Labels: WIP, new doc

#3523 Add closing brace to Redirect to HTTPS
  source/_docs/domains.md
Labels: EOM

#3518 Remove terminus auth:logout step for account switching.
  source/_docs/machine-tokens.md
Labels: CSE

#3517 Update nested-docroot.md
  source/_docs/nested-docroot.md
Labels: CSE

#3522 Drop text below screenshot images
  source/_docs/drupal-cache.md
Labels: CSE

#3495 change preposition
  source/_docs/upstream-updates.md
Labels: CSM

#3494 Add note about customizing lock page.
  source/_docs/security.md
Labels: CSE
