Repository pantheon-systems/documentation, pull requests merged in 2019-01, with the labels that each got.

#4364 Add iThemes Security to Known Issues list
  source/_docs/modules-plugins-known-issues.md
Labels: CSE, copy review, new content

#4366 Clarify that migrate_drush_path is only for Drupal 7
  source/_docs/timeouts.md
Labels: CSE, copy review

#4369 Correct indentation
  source/_docs/continuous-integration.md
Labels: External, fix content

#4368 Add large WP site migrate manually
  source/_docs/migrate.md
Labels: copy review

#4377 Fix bullet points on multidev access list
  source/_docs/multidev-faq.md
Labels: CSE

#4386 Note set-cookie overload issue
  source/_docs/cookies.md
Labels: copy review

#4388 added theme/plugin timeout workaround
  source/_docs/timeouts.md
Labels: technical review

#4375 Add instructions for WP Site Networks in Solr installation
  source/_docs/wordpress-solr.md
Labels: CSE, copy review, new content

#4389 tweaked transfer ownership partial and moved lines from site owner faq
  source/_docs/site-owner-faq.md
  source/_partials/content/transfer-ownership-billing-steps.html
Labels: technical review

#4392 downgrading caveat to custom certificates
  source/_docs/custom-certificates.md
Labels: copy review

#4390 Update PHP recommended vs. available versions
  source/_docs/php-versions.md
Labels: copy review

#4396 Update Subheader
  source/_docs/drupal-8-configuration-management.md
Labels: copy review

#4402 note proper code placement
  source/_docs/cache-control.md
Labels: copy review

#4401 Add redirection to known issues doc
  source/_docs/modules-plugins-known-issues.md
Labels: copy review, new content

#4380 add multiple url redirects
  source/_docs/redirects.md
Labels: copy review

#4324 Partner program docs updates
  source/_docs/add-client-site.md
  source/_docs/agency-tips.md
  source/_docs/annual-billing.md
  source/_docs/new-plans-faq.md
Labels: copy review

#4409 Add PHP version to CSV script example
  source/_docs/terminus/scripting.md
Labels: copy review

#4224 Update redis.md
  source/_docs/redis.md
Labels: External, technical review

#4408 add formatted list of Terminus command fields
  source/_docs/terminus/commands.md
  source/_partials/navbar.html
Labels: copy review, technical review

#4404 Expand HTTPS provision warning
  source/_docs/guides/launch/03-domains.md
Labels: copy review, new content

#4398 note mysql connection security
  source/_docs/mysql-access.md
Labels: copy review

#4420 update SSO documentation
  source/_docs/sso-organizations.md
Labels: pantheor

#4421 clarifies Multidev EDU availability
  source/_docs/multidev-faq.md
  source/_docs/organizations.md
Labels: copy review
