Repository pantheon-systems/documentation, pull requests merged in 2019-08, with the labels that each got.

#4965 Domain Masking/ Advanced CDN to Platform Considerations
  source/content/platform-considerations.md
Labels: gatsby-prerelease

#4968 fix broken contributor images
  source/data/contributor.yaml
Labels: In Progress

#4902 Solr without Multidev
  source/content/solr-drupal-8.md
Labels: Technical Review

#4813 Fix Symlink Path
  source/content/assuming-write-access.md
Labels: Technical Review

#4892 [CORE-1429] Updated DNS instructions to use A records instead of CNAME
  source/_partials/content/configure-dns.html
  source/_partials/content/standard-dns-config.html
  source/_partials/content/standard-dns-config2.html
  source/content/dns-providers/1-and-1.md
  source/content/dns-providers/123-reg.md
  source/content/dns-providers/akamai.md
  source/content/dns-providers/bluehost.md
  source/content/dns-providers/dns-made-easy.md
  source/content/dns-providers/dnsimple.md
  source/content/dns-providers/dreamhost.md
  source/content/dns-providers/dyn.md
  source/content/dns-providers/easy-dns.md
  source/content/dns-providers/enom.md
  source/content/dns-providers/fasthosts.md
  source/content/dns-providers/gandi.md
  source/content/dns-providers/godaddy.md
  source/content/dns-providers/google.md
  source/content/dns-providers/hostgator.md
  source/content/dns-providers/hover.md
  source/content/dns-providers/microsoft.md
  source/content/dns-providers/name-com.md
  source/content/dns-providers/namecheap.md
  source/content/dns-providers/network-solutions.md
  source/content/dns-providers/neustar.md
  source/content/dns-providers/register-com.md
  source/content/dns-providers/route53.md
Labels: Copy Review, gatsby-prerelease

#4983 Add missing metadata
  gatsby/src/pages/index.js
  gatsby/src/templates/landing.js
Labels: Site

#4990 fix link
  source/content/solr-drupal-8.md
Labels: Fix Content, Pantheor

#4871 Added the solution when the fast velocity minify breaks the site
  source/content/modules-plugins-known-issues.md
Labels: CSE, New Content

#4878 s3fs_cors module
  source/content/drupal-s3.md
Labels: CHALLENGE, CSE, Fix Content

#4923 clarify downgrades + duplicate note re contact agency for preferred
  source/content/add-client-site.md
  source/content/site-plan.md
Labels: gatsby-prerelease

#5017 Update README
  CONTRIBUTING.md
  README.md
Labels: Fix Content

#5022 Fix typo on "External libraries on Pantheon" page
  source/content/external-libraries.md
Labels: External, Fix Content

#4949 multidev for gold support+ in faq
  source/content/multidev-faq.md
Labels: gatsby-prerelease

#4754 add empty upstream info and see also section
  source/content/composer.md
  source/content/guides/composer-convert.md
Labels: New Content, Technical Review

#5023 Fix typo in connecting domain launch essentials description.
  source/content/guides/launch/03-domains.md
Labels: Fix Content, Pantheor

#4744 expand manual migrate: before you begin
  source/content/migrate-manual.md
Labels: Copy Review, New Content

#4822 Added troubleshooting section on how to determine which is breaking the cache
  source/content/wordpress-sessions.md
Labels: CHALLENGE, CSE, Copy Review, New Content

#5018 update script paths
  gatsby/gatsby-config.js
  gatsby/package-lock.json
  gatsby/package.json
  gatsby/src/components/download/index.js
  source/content/backups.md
  source/content/nginx-access-log.md
  source/content/wp-config-php.md
Labels: Site

#5014 note that contract customers don't need to remove CC
  source/content/relaunch.md
Labels: New Content

#5032 content fixes and corrections
  source/content/custom-upstream.md
  source/content/settings-php.md
Labels: Fix Content

#5035 Registry Rebuild for D7
  source/content/drush.md
Labels: Fix Content

#4877 Explicitly say dbserver and, and a straight-up reference guide about …
  source/content/logs.md
Labels: CHALLENGE

#4977 Update path pattern to 1.17.x
  source/content/shibboleth-sso.md
Labels: Copy Review, External, Fix Content

#5047 Bad Links Abound
  gatsby/src/layout/call-to-action/index.js
  gatsby/src/layout/footer/index.js
  source/changelogs/2017-05-01-May.md
  source/changelogs/2019-06-01-June.md
  source/content/annual-billing.md
  source/content/create-sites.md
  source/content/drupal-cron.md
  source/content/guides/composer-convert.md
  source/content/guides/edt/08-going-live.md
  source/content/modules.md
  source/content/pantheon_stripped.md
  source/content/unwind-drupal-multisite.md
  source/data/contributor.yaml
  source/data/landings.yaml
  source/docs/assets/css/main.css
Labels: Copy Review

#5042 Adjust Symlink Examples
  source/content/assuming-write-access.md
Labels: Copy Review, Fix Content

#5054 Update the Billing Information screenshot and steps
  source/content/guides/launch/02-plans.md
  source/images/choose-card.png
Labels: Copy Review

#5056 WebOps All the Things!
  source/content/cache-control.md
  source/content/caching-advanced-topics.md
  source/content/composer.md
  source/content/custom-upstream.md
  source/content/domains.md
  source/content/drupal-8-cache.md
  source/content/drupal-cache.md
  source/content/git-faq.md
  source/content/git.md
  source/content/global-cdn.md
  source/content/guides/build-tools/01-introduction.md
  source/content/guides/build-tools/09-update.md
  source/content/guides/frontend-performance.md
  source/content/guides/launch/02-plans.md
  source/content/guides/quickstart/10-next-steps.md
  source/content/https.md
  source/content/kill-mysql-queries.md
  source/content/local-development.md
  source/content/multidev.md
  source/content/new-relic.md
  source/content/pantheon-workflow.md
  source/content/pantheon-yml.md
  source/content/professional-services.md
  source/content/quicksilver.md
  source/content/redis.md
  source/content/sftp.md
  source/content/solr-drupal-7.md
  source/content/solr-drupal-8.md
  source/content/solr.md
  source/content/terminus.md
  source/content/wordpress-solr.md
  source/partials/composer-fundamentals.md
Labels: Fix Content

#5053 Improve README and style-guide
  README.md
  style-guide.md
Labels: External, Fix Content

#4998 HTTPS/HSTS by default
  source/content/custom-certificates.md
  source/content/guides/edt/08-going-live.md
  source/content/guides/launch/05-redirects.md
  source/content/hsts.md
  source/content/http-to-https.md
  source/content/https.md
  source/content/pantheon-yml.md
  source/partials/hsts.md
  source/partials/secure-only-tlds.md
Labels: Copy Review

#5070 Update install.md
  source/content/terminus/install.md
Labels: External, Fix Content

#5067 Reference Terminus Rsync Plugin in rsync & sftp guide
  source/content/rsync-and-sftp.md
Labels: Copy Review

#5068 Fix GitHub links
  gatsby/src/components/github/index.js
Labels: Technical Review

#4893 Added the plugin option for wp search replace
  source/content/wordpress-broken-links.md
  source/images/wp-migrate-db-setting.png
  source/partials/search-replace-domains.md
Labels: Copy Review
