Repository pantheon-systems/documentation, pull requests merged in 2019-03, with the labels that each got.

#4521 Added wp rocket issues and resolution
  source/_docs/modules-plugins-known-issues.md
Labels: technical review

#4531 March Changelog
  source/_changelogs/2019-03-01-March.md
  source/_partials/changelog_preview.twig
Labels: copy review

#4488 Add password reset options
  source/_docs/resetting-passwords.md
Labels: CSE, copy review

#4536 Removing Glossary reference to the advanced tab
  source/_docs/guides/quickstart/02-user-dashboard.md
Labels: copy review

#4539 Fix pantheon.upstream.yml in snippets
  source/_docs/nested-docroot.md
Labels: fix content, technical review

#4534 Update custom-certificates.md
  source/_docs/custom-certificates.md
Labels: copy review

#4542 Update EU DNS instructions
  source/_docs/eu-region.md
Labels: copy review

#4545 adds banner, tests with mix of md and html
  source/_docs/guides/build-tools/01-introduction.md
  source/_docs/guides/drupal-8-commerce.md
  source/_docs/guides/drupal-8-composer-no-ci.md
  source/_docs/guides/phpstorm-composer.md
  source/_views/doc.html
Labels: in progress

#4544 note Multidev requirement
  source/_docs/guides/build-tools/01-introduction.md
  source/_docs/guides/drupal-8-commerce.md
  source/_docs/guides/drupal-8-composer-no-ci.md
  source/_docs/guides/phpstorm-composer.md
  source/_views/doc.html
  source/_views/guide.html
Labels: copy review

#4541 update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: copy review

#4538 update language around ownership transfer
  source/_partials/content/transfer-ownership-billing-intro.html
Labels: copy review

#4473 add solr schema verification skip to troubleshooting
  source/_docs/solr-drupal-8.md
Labels: CHALLENGE, copy review

#4540 Rreplace dir tree with GH Links
  source/_docs/migrate-manual.md
  source/_partials/content/code.html
Labels: copy review, fix content

#4524 SimpleTests
  app/config/sculpin_site.yml
  source/_docs/continuous-integration.md
Labels: External, new content

#4533 add composer version note
  source/_docs/guides/build-tools/02-create-project.md
  source/_docs/guides/composer-convert.md
  source/_docs/guides/drupal-8-commerce.md
  source/_docs/guides/drupal-8-composer-no-ci.md
  source/_partials/content/composer-updating.html
Labels: copy review, new content

#4563 use deploy tokens for Gitlab custom upstreams
  source/_docs/create-custom-upstream.md
  source/docs/assets/images/gitlab-deploy-token.png
  source/docs/assets/images/gitlab-reporter.png
Labels: External, copy review, fix content, in progress

#4556 Explain Invitation Acceptance Steps and Gotchas
  source/_docs/add-client-site.md
  source/docs/assets/images/dashboard/add-card.png
  source/docs/assets/images/dashboard/invitation-new-account.png
  source/docs/assets/images/dashboard/invitation-to-pay.png
Labels: copy review

#4551 Ps documentation page update v2
  source/_docs/load-and-performance-testing.md
  source/_docs/migrate-manual.md
  source/_docs/professional-services.md
Labels: in progress

#4573 Note that Mac users can install Redis with Homebrew
  source/_docs/redis.md
Labels: CSE

#4580 FEAT-651: Sodium replaces Mcrypt in PHP 7.2 and later
  source/_docs/application-containers.md
Labels: Hold for Release

#4586 change instances of Wordpress to WordPress
  source/_changelogs/2016-12-01-December.md
  source/_changelogs/2017-01-01-January.md
  source/_docs/email.md
  source/_docs/filezilla.md
  source/_docs/guides/pingdom-uptime-check.md
  source/_docs/guides/sendgrid.md
  source/_docs/logs.md
  source/_docs/migrate-manual.md
  source/_docs/platform-considerations.md
  source/_docs/wp-config-php.md
Labels: Copy Review

#4583 Docs audit
  source/_docs/continuous-integration.md
  source/_docs/drush.md
  source/_docs/errors-and-server-responses.md
  source/_docs/hyperdb.md
  source/_docs/relaunch.md
  source/_docs/server_name-and-server_port.md
  source/_docs/site-owner-faq.md
  source/_docs/support.md
  source/_docs/team-management.md
  source/docs/assets/images/dashboard/add-additional-domains.png
  source/docs/assets/images/dashboard/add-first-domain.png
  source/docs/assets/images/dashboard/connect-custom-domain.png
  source/docs/assets/images/dashboard/details-page.png
  source/docs/assets/images/dashboard/direct-download-archive.png
  source/docs/assets/images/dashboard/direct-download-backup.png
  source/docs/assets/images/dashboard/drupal-guided-migrate.png
  source/docs/assets/images/dashboard/drush-aliases.png
  source/docs/assets/images/dashboard/sandbox-make-owner.png
  source/docs/assets/images/dashboard/site-dashboard-image.png
  source/docs/assets/images/dashboard/support-tab.png
Labels: Copy Review

#4585 Sodium not available on PHP 7.2
  source/_docs/application-containers.md
Labels: Copy Review, Fix Content, Pantheor

#4576 specify redirect logic location and link to detailed above
  source/_docs/redirects.md
Labels: Feedback

#4605 update community page
  source/_docs/power-users.md
Labels: Copy Review

#4578 expand instructions for expiring cached assets
  source/_docs/caching-advanced-topics.md
Labels: Technical Review

#4612 Add CC to Sandbox sites
  source/_docs/site-billing.md
Labels: Technical Review

#4555 New Guide: Behat
  source/_docs/guides/behat.md
  source/docs/assets/images/guides/behat-output.png
Labels: Copy Review, New Doc, Pantheor

#4620 Add an option for redirecting static files
  source/_docs/redirects.md
Labels: CSE, Copy Review

#4590 list additional issues
  source/_docs/modules-plugins-known-issues.md
Labels: Copy Review, New Content

#4626 updates to Cloudflare configuration
  source/_docs/dns-providers/cloudflare.md
  source/docs/assets/images/cloudflare-ssl.png
Labels: Copy Review, Fix Content

#4595 fix GitLab instructions
  source/_docs/create-custom-upstream.md
  source/docs/assets/images/gitlab-api.png
Labels: Copy Review

#4627 Update Org FAQ answer
  app/config/sculpin_site.yml
  source/_docs/organization-faq.md
Labels: Copy Review, Fix Content

#4588 note that locked environments aren't cached
  source/_docs/security.md
Labels: Copy Review, New Content
