Repository pantheon-systems/documentation, pull requests merged in 2019-09, with the labels that each got.

#4763 Update drupal-caching-modules.md
  source/content/drupal-caching-modules.md
Labels: Technical Review

#4943 Update documentation on Drush + mysql
  source/content/drush.md
Labels: Technical Review

#4919 Add -all option to upstream:list
  source/content/start-state.md
Labels: External, Fix Content

#4875 Added possible answers in this repo for multisite
  source/content/guides/multisite/01-introduction.md
Labels: CHALLENGE, CSE, New Content

#5086 Added subdirectory wildcard redirect
  source/content/redirects.md
Labels: CSE, New Content

#5074 Add warning to Build Tools guide
  source/content/guides/build-tools/01-introduction.md
Labels: In Progress

#5065 Replace bullets with table
  source/partials/hsts.md
Labels: Copy Review

#5088 [DOC-5] guide width
  gatsby/src/pages/contributors.js
  gatsby/src/pages/search.js
  gatsby/src/templates/contributor.js
  gatsby/src/templates/guide.js
  gatsby/src/templates/terminuspage.js
Labels: Copy Review

#5098 September changelog
  gatsby/gatsby-node.js
  gatsby/src/pages/index.js
  source/changelogs/2019-04-01-April.md
  source/changelogs/2019-05-01-May.md
  source/changelogs/2019-06-01-June.md
  source/changelogs/2019-07-01-July.md
  source/changelogs/2019-08-01-August.md
  source/changelogs/2019-09-01-September.md
Labels: Copy Review

#5103 update redirects page and snippet
  source/content/guides/launch/05-redirects.md
  source/partials/_redirects.md
Labels: Technical Review

#4898 Add details on how to enable the ajax frontend search with screenshots
  source/content/wordpress-solr.md
  source/images/add-solr-widget.png
  source/images/solr-widget-settings.png
Labels: Copy Review

#5113 Fix UTM redirection example
  source/content/pantheon_stripped.md
Labels: CSE, Copy Review, Fix Content

#5132 Illustrate using pipe grep fu to get your new tag.
  source/content/hotfixes.md
Labels: Copy Review, External, New Content

#5131 Update redis.md
  source/content/redis.md
Labels: CSE, Copy Review, New Content

#5139 Fix Partial, add Linter Config
  .markdownlint.json
  source/content/domains.md
Labels: Copy Review

#5140 Fixing spelling error
  source/content/guides/launch/04-configure-dns.md
Labels: External, Fix Content

#5133 Add sitemap
  gatsby/gatsby-config.js
  gatsby/package.json
  gatsby/src/pages/index.js
Labels: Site, Technical Review

#4676 Update MySQL Slow Log page
  .circleci/config.yml
  scripts/merge_conflicts.sh
  source/content/mysql-slow-log.md
Labels: CSE, Copy Review

#5142 fix: twitter button renders inconsistently
  gatsby/gatsby-ssr.js
  gatsby/src/components/twitter.js
  gatsby/src/components/twitter/index.js
  gatsby/src/components/twitter/style.css
Labels: Site, Technical Review

#5141 Lando Guide
  source/content/guides/lando.md
  source/data/contributor.yaml
  source/images/guides/lando/lando-choose-recipe.png
  source/images/guides/lando/lando-installer.png
  source/images/guides/lando/lando-start.png
Labels: Copy Review, External, New Doc

#5146 [FEAT-723] Allow Swiftbot user-agent on non-live environments (robots.txt)
  source/content/bots-and-indexing.md
Labels: New Content, Pantheor

#5158 update WP Doc link
  source/content/resetting-passwords.md
Labels: Copy Review

#5154 [fix] Subtopics alignment
  gatsby/src/layout/subtopic-group/style.css
  gatsby/src/layout/topic-group/index.js
  source/data/landings.yaml
Labels: Site, Technical Review

#5137 Update Cloudflare instructions for A records
  source/content/dns-providers/cloudflare.md
  source/images/cf-caa-final.png
  source/images/cf-caa.png
  source/images/cloudflare-always-https.png
  source/images/cloudflare-dns-only.png
  source/images/cloudflare-full.png
  source/images/cloudflare-ssl.png
Labels: Copy Review

#5162 Add clearer notes on drush ard deprecation
  source/content/migrate.md
Labels: Copy Review, Fix Content

#5145 minor grammar/caps changes, and adding to guides page
  gatsby/src/templates/landing.js
  source/content/guides/lando.md
  source/data/landings.yaml
Labels: Copy Review, Fix Content
