Repository pantheon-systems/documentation, pull requests merged in 2019-04, with the labels that each got.

#4582 add troubleshooting section for Edge browser
  source/_docs/machine-tokens.md
Labels: Copy Review

#4603 Removing depreciated log files from list
  source/_docs/logs.md
Labels: Technical Review

#4601 Changed <site>.<env> to <site>.test
  source/_docs/drupal-8-configuration-management.md
Labels: Technical Review

#4577 add FAQ re: surrogate-key-raw header
  source/_docs/global-cdn.md
  source/docs/assets/images/surrogate-key-raw-example.png
Labels: Copy Review

#4572 Change recommended location for the Drush aliases file
  source/_docs/drush.md
Labels: External

#4623 EU International Region Limited Availability
  source/_docs/eu-region.md
  source/docs/assets/images/create-site-eu.png
  source/docs/assets/images/settings-about-site-region-eu.png
  source/docs/assets/images/x-served-by-eu.png
Labels: Technical Review

#4647 Added slight clarification for CMS robots.txt
  source/_docs/bots-and-indexing.md
Labels: CSE, Copy Review

#4648 Distinguish btn-contribute when it's focused
  app/config/sculpin_site.yml
  source/docs/assets/css/main.css
Labels: External, Site

#4654 Copy edits to EU Region doc
  source/_docs/eu-region.md
  source/docs/assets/images/create-site-eu.png
Labels: Copy Review

#4634 FAQ answer to running tail on logs
  source/_docs/logs.md
Labels: Copy Review, New Content

#4640 April Changelog
  source/_changelogs/2019-04-01-April.md
  source/_partials/changelog_preview.twig
Labels: Copy Review

#4561 Secure Only Top Level Domains
  source/_docs/domains.md
  source/_docs/vanity-domains.md
  source/_partials/content/secure-only-tlds.html
Labels: Copy Review

#4661 Update 08-onserver-dev-part1.md
  source/_docs/guides/quickstart/08-onserver-dev-part1.md
Labels: Fix Content, Pantheor

#4662 Terminus Example Usage: Command Structure
  source/_docs/terminus/examples.md
  source/docs/assets/images/terminus-wp-cli-example.png
Labels: CSM, Copy Review

#4362 Note that Redis maxmemory varies based on plan level
  source/_docs/redis.md
Labels: In Progress

#4671 add clarifications concerning transferring sites with preferred pricing.
  source/_partials/content/invite-to-pay.html
Labels: Copy Review

#4672 Clarify that Redis is tied to plan, not environment
  source/_docs/redis.md
Labels: CSE

#4673 Copy edits for Redis FAQs
  source/_docs/redis.md
Labels: CSE, Copy Review

#4675 EU DR now available
  source/_docs/eu-region.md
Labels: In Progress

#4668 list requirements for new CSR
  source/_docs/custom-certificates.md
Labels: Copy Review

#4664 note php.ini is not writable
  source/_docs/platform-considerations.md
Labels: Copy Review

#4665 mention CNAME
  source/_docs/guides/launch/04-configure-dns.md
Labels: Copy Review

#4678 Update ldap-and-ldaps.md
  source/_docs/ldap-and-ldaps.md
Labels: New Content, Pantheor, Technical Review

#4691 Added some sample code to fix issue un Media Uploader HTTP error
  source/_docs/wordpress-known-issues.md
Labels: Copy Review

#4689 Adding a note that users can skip the htaccess configuration in the Multisite setup
  source/_docs/guides/multisite/03-config.md
Labels: Copy Review

#4692 Update sso-organizations.md
  source/_docs/sso-organizations.md
Labels: Copy Review

#4700 update contrib reference from Terminus 1.x to 2.x
  source/_docs/terminus.md
Labels: CSM, Fix Content
