Repository pantheon-systems/documentation, pull requests merged in 2022-12, with the labels that each got.

#7985 DOCO-753 Bots and Indexing Disallow List
  source/content/bots-and-indexing.md
Labels: Pantheor

#7987 DOCO-752 Drupal 10 SimpleSAMLphp Compatibility
  source/content/shibboleth-sso.md
Labels: Pantheor, Drupal

#7991 [OTTO-3085][OTTO-3082] Autopilot Error: Upstreams Could Not Be Merged
  source/content/guides/autopilot/07-troubleshoot.md
Labels: Pantheor, autopilot

#8003 Refresh New Relic docs, update screenshots
  source/content/guides/new-relic/02-activate-new-relic.md
  source/images/integrations/newrelic/new-relic-get-started.png
  source/images/integrations/newrelic/new-relic-summary.png
Labels: Pantheor

#7877 Add Cache Hit Ratio to Metrics
  source/partials/traffic-dl.md
Labels: Pantheor

#7984 [CMS-879] Add 8.2 to php versions table.
  source/partials/_php-versions.md
Labels: New Content, Pantheor

#8013 update symlink for fast velocity minify plugin
  source/content/plugins-known-issues.md
Labels: Pantheor

#8014 Add dashboard step to Redis Drupal 9 instructions
  source/content/guides/object-cache/02-enable-object-cache.md
Labels: Pantheor

#8019 Clarify language and remove yml reference
  source/content/guides/domains/08-domain-hijacking.md
Labels: CSE, Pantheor

#8018 DOCO-724 Filesystem Guide
  source/changelogs/2016-03-01-March.md
  source/content/files.md
  source/content/guides/filesystem/01-introduction.md
  source/content/guides/filesystem/02-batch-files.md
  source/content/guides/filesystem/03-large-files.md
  source/content/guides/filesystem/04-files-directories.md
  source/content/guides/filesystem/05-tmp.md
  source/content/guides/filesystem/06-troubleshooting.md
  source/content/guides/platform-considerations/04-files-directories.md
  source/content/guides/quickstart/06-clone-live-to-dev.md
  source/content/guides/secure-development/04-private-paths.md
  source/content/guides/sftp/01-introduction.md
  source/content/guides/sftp/04-rsync-and-sftp.md
  source/content/guides/sftp/05-vscode-sftp.md
  source/content/guides/wordpress-configurations/08-wordpress-s3.md
  source/content/guides/wordpress-pantheon/07-wordpress-developers.md
  source/content/horizontal-scalability.md
  source/content/migrate-wordpress-site-networks.md
  source/content/modules-known-issues.md
  source/content/overview/platform.md
  source/content/overview/products.md
  source/content/pantheon-workflow.md
  source/content/pantheon-yml.md
  source/content/rsync-and-sftp.md
  source/content/tmp.md
  source/data/landings.yaml
  source/partials/migrate/troubleshooting-drupal.md
  source/partials/migrate/troubleshooting-wordpress.md
  source/partials/tmp-directory.md
Labels: Redirect, Guidification

#7962 Enterprise Billing Center and Site Portfolio Report Update
  source/content/guides/enterprise-billing-center/01-introduction.md
  source/content/guides/enterprise-billing-center/02-invoices.md
  source/content/guides/enterprise-billing-center/03-site-portfolio-report.md
  source/content/guides/enterprise-billing-center/04-interacting.md
  source/content/guides/enterprise-billing-center/05-faq.md
  source/content/guides/site-portfolio-report/03-faq.md
  source/data/landings.yaml
  source/images/site-portfolio-report-dashboard-portfolio-report-section.png
  source/images/site-portfolio-report-no-portfolio-section.png
Labels: Hold for Release, Redirect

#8020 OTTO-2557 Autopilot Do Not Deploy
  source/content/guides/autopilot/03-enable-autopilot.md
  source/content/guides/autopilot/04-tests-results.md
  source/content/guides/autopilot/08-autopilot-faq.md
  source/images/autopilot/autopilot-destination-frequency.png
Labels: Pantheor, autopilot, Hold for Release

#8034 DOCO-777 Remove New Relic Registered Symbol in Frontmatter
  source/content/guides/pagerduty/01-introduction.md
  source/content/guides/pagerduty/02-monitor.md
  source/content/guides/pagerduty/03-schedule.md
  source/content/guides/pagerduty/04-notify.md
  source/content/guides/pagerduty/05-slack.md
  source/content/guides/pagerduty/06-next-steps.md
Labels: Fix Content, Pantheor

#8035 DOCO-778 New Relic Ping Monitoring
  source/content/guides/new-relic/03-monitor-new-relic.md
  source/content/guides/new-relic/06-troubleshoot-new-relic.md
Labels: Pantheor

#8030 DOCO-776 Reduce Large Repos
  source/content/guides/filesystem/03-large-files.md
  source/content/guides/git/02-git-config.md
  source/content/guides/git/03-collaborative-development.md
  source/content/guides/git/04-useful-commands.md
  source/content/guides/git/05-undo-commits.md
  source/content/guides/git/06-resolve-merge-conflicts.md
  source/content/guides/git/07-git-faq.md
  source/content/guides/git/08-troubleshooting.md
  source/content/reducing-large-repos.md
Labels: Pantheor, Redirect
