Repository pantheon-systems/documentation, pull requests merged in 2023-02, with the labels that each got.

#8093 Update pantheon-yml.md
  source/content/pantheon-yml.md
Labels: Pantheor

#8086 DOCO-789 Add DDEV to Local Development
  source/content/guides/local-development/04-jenkins.md
  source/content/guides/local-development/05-lando-wordpress.md
  source/content/guides/local-development/06-ddev.md
  source/content/guides/local-development/07-wordpress-phpstorm.md
  source/content/guides/local-development/08-drupal-phpstorm.md
  source/content/guides/local-development/09-graphql-requests.md
  source/content/guides/local-development/10-cygwin-windows.md
  source/content/guides/local-development/11-visual-studio-code.md
Labels: New Content, Pantheor, Drupal, DO NOT MERGE

#8079 DOCO-804 Terminus Autopilot Plugin
  source/content/terminus/08-directory.md
Labels: Pantheor, autopilot, Terminus

#8092 DOCO-853 Hummingbird Assumed Write Access
  source/content/plugins-known-issues.md
Labels: wp

#8094 DOCO-849 Pantheon Core Files
  source/content/code.md
  source/content/migrate-manual.md
Labels: Fix Content, New Content

#8097 DOCO-855 Core Updates
  source/content/core-updates.md
Labels: Fix Content

#8104 Removing frivolous trailing bracket from page
  source/content/guides/multisite/03-config.md
Labels: Fix Content

#8107 recommend tableplus for accessing mysql
  source/content/guides/mariadb-mysql/02-mysql-access.md
Labels: Pantheor

#8099 DOCO-852 Drush Site Aliases
  source/content/guides/drush/06-drush-aliases.md
Labels: New Content, Drupal, Terminus

#8103 DOCO-114 Cloudflare Front-End Sites
  source/content/dns-providers/cloudflare.md
  source/content/guides/decoupled-sites/06-faq.md
Labels: Pantheor

#8123 Prepare main for PFE
  source/content/style-guide.md
  source/partials/terminus-guide/eol.md
  src/algolia/index.js
Labels: Site

#8126 [PFE-01] Fix Style Guide
  source/content/style-guide.md
Labels: New Content

#8100 [PFE-02] Update Search Page To Use Algolia
  gatsby-config.js
  src/algolia/config.js
  src/components/search/hitComps.js
  src/components/search/index.js
  src/components/search/input.js
  src/layout/header/index.js
  src/layout/layout/index.js
  src/layout/layout/style.css
  src/pages/search.js
  src/pages/style.css
Labels: External

#8136 [PFE] docs.pantheon.io
  gatsby-config.js
Labels: Site

#8113 [hold for FE] add max_input_vars
  source/content/guides/platform-considerations/06-php-platform.md
Labels: Pantheor

#8101 [CMSP-221] Release notes for contact support line removal
  source/content/start-states/wordpress.md
Labels: Pantheor

#8108 DOCO-848 Build and Deploy Terminology
  source/content/guides/composer.md
  source/content/guides/git/01-introduction.md
  source/content/guides/integrated-composer/01-introduction.md
  source/content/guides/integrated-composer/05-ic-upstreams.md
  source/partials/build-deploy-terminology.md
  source/partials/ic-upstream-structure.md
Labels: New Content

#8114 DOCO-851 Shibboleth Alternatives
  source/content/shibboleth-sso.md
Labels: External

#8116 DOCO-824 Rsync File Transfer Steps
  source/content/migrate-manual.md
Labels: Fix Content, External

#8117 [hold for fe] Update D10 Custom Upstream
  source/content/guides/git/06-resolve-merge-conflicts.md
Labels: drupal-10

#8118 DOCO-862 Deprecate EDT Guide
  source/changelogs/2019-04-01-April.md
  source/content/guides/edt/01-essentialdevelopertraining.md
  source/content/guides/edt/02-introduction-and-architecture.md
  source/content/guides/edt/03-developer-workflow.md
  source/content/guides/edt/04-multidev.md
  source/content/guides/edt/05-terminus-cli.md
  source/content/guides/edt/06-quicksilver-external-integrations.md
  source/content/guides/edt/07-performance.md
  source/content/guides/edt/08-going-live.md
  source/data/landings.yaml
  source/partials/additionalResources/lw1.md
  source/partials/additionalResources/lw4.md
Labels: Pantheor

#8122 DOCO-827 Terminus Install and Update Content Changes
  source/content/terminus/02-install.md
  source/content/terminus/11-updates.md
  src/templates/terminuspage.js
Labels: External, Terminus

#8133 DOCO-854 Drupal IMCE Module
  source/content/modules-known-issues.md
Labels: External, Drupal

#8138 DOCO-868 Remove Duplicated Docs
  source/content/cms-admin.md
  source/content/code.md
  source/content/kill-mysql-queries.md
  source/content/port-2222.md
  source/content/rsync-and-sftp.md
  source/content/security.md
  source/content/sftp.md
Labels: Pantheor

#8090 [CMS-1257] Custom upstreams commands recent changes.
  source/content/guides/custom-upstream/02-create-custom-upstream.md
  source/content/guides/custom-upstream/03-edit-custom-upstream.md
  source/content/guides/integrated-composer/05-ic-upstreams.md
  source/partials/ic-upstream-structure.md
Labels: Pantheor

#8125 [CMSP-10] Replace WordPress Site Network(s) with WordPress Multisite(s)
  source/changelogs/2017-11-01-November.md
  source/changelogs/2018-01-01-January.md
  source/changelogs/2022-05-01-May.md
  source/content/agency-tips.md
  source/content/faq.md
  source/content/guides/git/06-resolve-merge-conflicts.md
  source/content/guides/localdev/04-troubleshoot-support.md
  source/content/guides/multisite/01-introduction.md
  source/content/guides/multisite/02-considerations.md
  source/content/guides/multisite/03-config.md
  source/content/guides/multisite/04-multisite-governance.md
  source/content/guides/multisite/05-workflows.md
  source/content/guides/multisite/06-debug.md
  source/content/guides/platform-considerations/02-platform-site-info.md
  source/content/guides/professional-services/02-website-migration-service.md
  source/content/guides/wordpress-developer/06-wordpress-cron.md
  source/content/guides/wordpress-pantheon/02-create-wp-site.md
  source/content/guides/wordpress-pantheon/03-migrate-existing-wp-site.md
  source/content/guides/wordpress-pantheon/09-wp-content-managment.md
  source/content/guides/wp-cli/03-wp-cli-global-parameters.md
  source/content/migrate-manual.md
  source/content/migrate-wordpress-multisite.md
  source/content/start-states/wordpress.md
  source/content/style-guide.md
  source/content/wordpress-known-issues.md
  source/data/landings.yaml
  source/partials/migrate/manual-when-wordpress.md
  source/partials/notes/multisite.md
Labels: Pantheor, wp, Redirect

#8067 DO NOT MERGE DOCO-791 Better insight into roles
  source/content/guides/account-mgmt/workspace-sites-teams/07-teams.md
Labels: New Content

#8158 gatsby 4
  gatsby-config.js
  package-lock.json
  package.json
Labels: Site

#8164 [CMS-1179] Release notes for upcoming drupal-composer-managed release supporting D10
  source/content/start-states/drupal-composer-managed.md
Labels: New Doc, Pantheor, Drupal

#8170 Update 02-enable-object-cache.md to prevent WP Errors
  source/content/guides/object-cache/02-enable-object-cache.md
Labels: First Contribution!

#8162 DOCO-871 Update Migration Guide
  source/content/guides/drupal/drupal-hosted-createempty-md/05-composer-upstream.md
Labels: Fix Content

#8172 readme: PFE and Gatsby 4
  README.md
Labels: Site

#8175 Fix small typo in docs.
  source/content/core-updates.md
Labels: Fix Content, Pantheor

#8188 [CMSO-1299] Drupal 10 Availability
  source/content/drupal-10.md
  source/content/drupal.md
  source/content/supported-drupal.md
Labels: Pantheor
