Repository pantheon-systems/documentation, pull requests merged in 2023-01, with the labels that each got.

#8043 DOCO-780 Log Files Update
  source/content/guides/logs-pantheon/01-introduction.md
Labels: Fix Content, Pantheor

#8045 php error logs description missed details
  source/content/guides/logs-pantheon/01-introduction.md
Labels: Pantheor

#8042 DOCO-781 WP Site Networks rsync File Transfer
  source/content/migrate-wordpress-site-networks.md
Labels: Fix Content, Pantheor

#8050 Fixing incorrect link within Solr Docs
  source/content/solr.md
Labels: Pantheor

#8049 DOCO-784 Add cURL Debug Data to Support Guide
  source/content/guides/support/06-curl.md
  source/content/guides/support/07-faq.md
Labels: New Content, Pantheor

#8064 Minor update
  source/content/guides/solr-drupal/02-solr-drupal.md
Labels: Pantheor

#8061 Algolia Implementation
  gatsby-config.js
  package-lock.json
  package.json
  src/algolia/config.js
  src/algolia/index.js
  src/components/search/hitComps.js
  src/components/search/index.js
  src/components/search/input.js
  src/components/search/style.css
  src/components/search/styles.js
  src/layout/header/index.js
  src/layout/header/style.css
Labels: First Contribution!

#8060 Update 04-automate-log-downloads.md
  source/content/guides/logs-pantheon/04-automate-log-downloads.md
Labels: New Content, Pantheor

#8063 [BUGS-5709] Add release notes for forthcoming WordPress upstream update
  source/content/start-states/wordpress.md
Labels: New Content, Pantheor

#8081 Add nvmrc file
  .nvmrc
Labels: Pantheor

#8080 [CMSO-1182] Add phpstan/extension-installer notice
  source/content/drupal-10.md
Labels: Pantheor

#8062 Specify key type for ssh-keygen
  source/content/ssh-keys.md
Labels: Pantheor

#8068 [CMS-1215] EOL Terminus 2.
  source/content/terminus/10-supported-terminus.md
  source/partials/terminus-guide/eol.md
  source/partials/terminus-guide/php.md
Labels: Pantheor, Terminus
