Repository pantheon-systems/documentation, pull requests merged in 2023-08, with the labels that each got.

#8550 Update plugins-known-issues.md
  source/content/plugins-known-issues.md
Labels: Pantheor, First Contribution!

#8631 CMSP-303 OCP Installation
  source/content/guides/object-cache-pro/01-introduction.md
  source/content/guides/object-cache-pro/02-installing-configuring.md
  source/content/guides/object-cache/02-enable-object-cache.md
  source/content/guides/object-cache/03-redis-command-line.md
  source/content/guides/object-cache/05-troubleshoot-object-cache.md
  source/content/guides/wordpress-pantheon/04-wordpress-launch-check.md
  source/content/partials/remove-addons/wp-redis.md
  source/images/guides/object-cache-pro/pantheon-settings-addons.png
Labels: Product

#8596 DOCO-1025 Customer Scheduled Jobs
  source/content/customer-scheduled-cron-jobs.md
Labels: New Doc
