Repository pantheon-systems/documentation, pull requests merged in 2023-04, with the labels that each got.

#8237 Detailed Product Overview: Enterprise Billing Center
  source/content/overview/enterprise-billing-center.md
  source/content/overview/products.md
  source/images/enterprise-billing-center-invoice-report.jpg
  source/images/enterprise-billing-center.png
  src/templates/doc.js
Labels: New Doc

#8284 Cache ratio common causes, allow direct linking
  source/content/metrics.md
  source/partials/traffic-dl.md
Labels: Fix Content

#8264 CMSP-293-object-cache-pro-ea-docs
  source/content/guides/object-cache-pro/01-introduction.md
  source/content/guides/object-cache-pro/02-installing-configuring.md
  source/images/guides/object-cache-pro/object-cache-pro-analytics.png
  source/images/guides/object-cache-pro/pantheon-settings-addons.png
Labels: New Doc

#8303 [CMSP-12] Multisite search-replace EA
  source/content/guides/multisite/05-workflows.md
  source/content/guides/multisite/06-search-replace.md
  source/content/guides/multisite/07-debug.md
  source/content/pantheon-yml.md
Labels: New Content

#8299 DOCO-128 Decoupled Static Indexing
  source/content/guides/decoupled/overview/02-considerations.md
Labels: decoupled-pre-ga

#8302 DOCO-959 Solr Version Update
  source/content/solr.md
  source/partials/solr-version.md
Labels: Fix Content

#8298 DOCO-966 Delete FE Site
  source/content/guides/account-mgmt/workspace-sites-teams/05-sites.md
  source/content/guides/decoupled/overview/01-introduction.md
  source/content/guides/decoupled/overview/05-manage-settings.md
  source/images/decoupled-confirm-deletion.png
  source/images/decoupled-delete-site.png
Labels: decoupled-pre-ga

#8308 Few minor WP doc updates
  source/content/guides/integrated-composer/01-introduction.md
  source/content/guides/multisite/01-introduction.md
  source/content/guides/multisite/02-considerations.md
Labels: Pantheor, wp

#8320 Optimize wp-options
  source/content/optimize-wp-options-table-autoloaded-data.md
Labels: Pantheor

#8318 show storage limit for sandbox sites
  source/content/guides/legacy-dashboard/02-create-sites.md
Labels: Pantheor

#8326 DOCO-388 WP Solr Index Quicksilver
  source/content/guides/quicksilver/02-install-script.md
Labels: Pantheor

#8292 Changes to Guided Migration Guide
  source/content/add-site-clone.md
  source/content/add-site-custom-upstream.md
  source/content/add-site-dashboard.md
  source/content/add-site.md
  source/content/doc-template.md
  source/content/guides/getstarted/06-addsite.md
  source/content/guides/getstarted/08-launch.md
  source/content/guides/migrate/acquia/01-introduction.md
  source/content/guides/migrate/guided/01-introduction.md
  source/content/guides/migrate/guided/05-migrate.md
  source/content/guides/migrate/kinsta/01-introduction.md
  source/content/guides/migrate/pagely/01-introduction.md
  source/content/guides/migrate/platformsh/01-introduction.md
  source/content/guides/migrate/wordpressvip/01-introduction.md
  source/content/guides/migrate/wpengine/01-introduction.md
  source/images/create-site-cms-both.png
  source/images/create-site-cms-drupal.png
  source/images/create-site-cms-wordpress.png
  source/images/launch-clone-dev-to-test.png
  source/images/launch-clone-test-to-live.png
  source/images/migrate-site-wp-blogvault.png
  source/partials/cms-dev.md
  source/partials/drupal/guide-note.md
  source/partials/live-initialize.md
  source/partials/migrate/faq-drupal.md
  source/partials/migrate/faq-general.md
  source/partials/migrate/faq-wordpress.md
  source/partials/migrate/manual-when-all.md
  source/partials/migrate/manual-when-drupal.md
  source/partials/migrate/manual-when-wordpress.md
  source/partials/migrate/migrate-drupal.md
  source/partials/migrate/migrate-wp.md
  source/partials/migrate/prepare.md
  source/partials/migrate/troubleshooting-migrate-general.md
  source/partials/migrate/troubleshooting-wordpress.md
  source/partials/test-initialize.md
Labels: Fix Content

#8332 DOCO-986-WP-Build-Hooks
  source/content/guides/decoupled/wp-backend-starters/07-build-hooks.md
Labels: decoupled-pre-ga

#8333 Fix typo on logs page
  source/content/guides/logs-pantheon/01-introduction.md
Labels: Fix Content

#8337 hide the skip to content bar a little more
  src/layout/header/style.css
Labels: Site, Site: Feature Request

#8346 Explain how to select the version of NodeJS
  source/content/guides/decoupled/overview/05-manage-settings.md
Labels: Pantheor

#8340 WordFence symlinks are relative to code root
  source/content/plugins-known-issues.md
Labels: Pantheor

#8349 Update primary-domain.md
  source/partials/primary-domain.md
Labels: New Content, Pantheor

#8351 Update migrate-wordpress-multisite.md
  source/content/migrate-wordpress-multisite.md
Labels: New Content, Pantheor

#8354 Multidev Link Update
  source/content/guides/drupal/drupal-hosted/01-introduction.md
Labels: Fix Content, Pantheor

#8356 DOCO-996 Docroot Link
  source/content/nested-docroot.md
Labels: Fix Content, Pantheor

#8329 [CMSP-319] Refrence sites-yml-validator util in WPMS search-replace docs
  source/content/guides/multisite/06-search-replace.md
Labels: Pantheor, wp

#8360 Added sample sites.yml inlined in the search replace docs for wpms
  source/content/guides/multisite/06-search-replace.md
Labels: Pantheor

#8362 Product Overview: Dashboard
  source/content/overview/dashboard.md
  source/images/dashboard/new-dashboard/site-dashboard.png
  source/images/dashboard/new-dashboard/sites.png
  source/images/dashboard/new-dashboard/teams.png
Labels: New Doc

#8365 DOCO-995 Pantheon yml Multidev
  source/content/guides/multidev/02-create-multidev.md
  source/content/pantheon-yml.md
Labels: New Content, Pantheor

#8366 Terminus Install Example
  source/content/terminus/02-install.md
Labels: Fix Content

#8369 DOCO-998 FES Node.js Versions
  source/content/guides/decoupled/overview/02-considerations.md
  source/content/guides/decoupled/overview/05-manage-settings.md
Labels: Pantheor

#8371 Drupal Gutenberg Link
  source/content/drupal.md
Labels: Fix Content, First Contribution!

#8367 DOCO-997 Multisites Object Cache Pro
  source/content/guides/object-cache-pro/02-installing-configuring.md
Labels: New Content

#8375 no longer recommend php 8.0
  source/partials/_php-versions.md
Labels: Pantheor

#8376 [CMSP-363] Update the doc to add more accurate guidance for OCP on WP Multisite
  source/content/guides/object-cache-pro/02-installing-configuring.md
Labels: Pantheor, wp

#8373 trackpageonlyifready
  gatsby-config.js
Labels: Site

#8383 Fixed broken link
  source/content/migrate-cpanel.md
Labels: Pantheor

#8382 DOCO-1005 WP Options Transient Data
  source/content/optimize-wp-options-table-autoloaded-data.md
Labels: Pantheor

#8394 DOCO-1010 WP Configuration Typo
  source/content/guides/wordpress-configurations/05-wordpress-cache-plugin.md
Labels: Fix Content
