Repository pantheon-systems/documentation, pull requests merged in 2024-06, with the labels that each got.

#9007 Visual Regression with Playwright
  tests/.gitignore
  tests/package-lock.json
  tests/package.json
  tests/playwright-tests/visuals.spec.ts
  tests/playwright.config.ts
  tests/readme.md
Labels: Site

#9040 Minor update caching-advanced-topics.md
  source/content/caching-advanced-topics.md
Labels: Fix Content, Pantheor

#9036 Remove gatsby-remark-embed-markdown to resolve dependabot alert #14
  package-lock.json
  package.json
Labels: Site, dependencies, High Priority

#9018 Feature/wecs 157 implement pagination for release notes
  src/components/releaseNotePopoverCategorySelector.js
  src/components/releaseNotesPager.js
  src/templates/releaseNotesListing/index.js
  src/templates/releaseNotesListing/style.css
Labels: Site

#8728 Remove D8 for Drupal Composer upstream
  source/content/migrate-manual.md
Labels: Needs SME, Pantheor

#8968 Eliminate CSS warnings from build process
  src/components/ReleaseNoteTeaser/index.js
  src/components/headerBody/index.js
  src/components/mdxWrapper.js
  src/components/partial.js
  src/layout/GuideLayout/index.js
  src/layout/header/index.js
  src/layout/layout/index.js
  src/pages/glossary.js
  src/pages/search.js
  src/templates/certificationpage.js
  src/templates/doc.js
  src/templates/guide.js
  src/templates/releaseNotePage.js
  src/templates/terminusCommand.js
  src/templates/terminuspage.js
  src/templates/video.js
  tests/playwright-tests/visuals.spec.ts
Labels: Site

#8731 Update the recommended s3 policy in s3 offload media
  source/content/guides/wordpress-developer/07-wordpress-s3.md
  source/images/guides/s3-access2-updated.png
  source/images/guides/s3-access2.png
Labels: Needs SME

#9029 Create release note for new Registration/login rollout
  source/images/release-notes/2024/New-Login.png
  source/images/release-notes/2024/Old-Login.png
  source/releasenotes/2024-06-12-login-update.md
Labels: release-notes

#8927 Add Media Bulk Upload to Incompatible Modules
  source/content/modules-known-issues.md
Labels: CSE
