Repository pantheon-systems/documentation, pull requests merged in 2024-07, with the labels that each got.

#9070 Update 05-advanced-curls.md - missing `Pantheon-Debug` header value
  source/content/guides/launch/05-advanced-curls.md
Labels: Fix Content, Pantheor

#8991 Create 2024-05-06-domain-validation.md
  source/releasenotes/2024-07-03-domain-validation.md
Labels: release-notes

#9059 Update bots-and-indexing.md
  source/content/bots-and-indexing.md
  source/releasenotes/2024-07-03-platform-robots-txt-now-supports-pope-tech.md
Labels: release-notes

#9071 Release note for WPCM 1.31.0
  source/releasenotes/2024-07-10-wordpress-composer-managed-1-31-0-update.md
Labels: Hold for Release

#9088 removing old links
  source/content/agency-tips.md
  source/content/guides/wordpress-configurations/02-plugins.md
  source/content/guides/wordpress-pantheon/06-plugins.md
  source/content/support.md
Labels: quick fix

#9034 New Site Feature: RSS Feed for Release Notes
  gatsby-config.js
  package-lock.json
  package.json
  src/templates/releaseNotePage.js
  src/templates/releaseNotesListing/index.js
  src/templates/releaseNotesListing/style.css
Labels: Site

#9091 Create 2024-07-12-rss-feed.md
  source/releasenotes/2024-07-12-rss-feed.md
Labels: release-notes

#8882 WordPress plugins: update the polylang cookie solution
  source/content/plugins-known-issues.md
Labels: PS, Pantheor, WordPress

#9077 [LOPS-2270] New Relic agent update release note.
  source/releasenotes/2024-07-16-new-relic-agent-update-released.md
Labels: Hold for Release, release-notes

#9109 CMSP-1022: WordPress 6.6 Release Notes
  source/releasenotes/2024-07-16-wordpress-6-6.md
Labels: release-notes

#9107 composer copy edits
  source/content/guides/integrated-composer/05-ic-upstreams.md
  source/content/partials/ic-upstream-structure.md
  source/content/partials/upstream-management-dependencies.md
Labels: quick fix

#9108 offboarding clarification
  source/content/guides/account-mgmt/workspace-sites-teams/07-teams.md
Labels: quick fix

#9106 correcting nest docroot instructions
  source/content/nested-docroot.md
Labels: quick fix

#9105 adding alert for dev and multidev caching
  source/content/caching-advanced-topics.md
Labels: WordPress, quick fix

#9103 8913 typo
  source/content/partials/migrate/drupal-custom-code.md
Labels: quick fix

#9100 8658 php version link
  source/content/guides/php/02-php-versions.md
Labels: quick fix

#9099 Updating maching token URL
  source/content/machine-tokens.md
Labels: quick fix

#9087 Updating empty upstream page
  source/content/static-site-empty-upstream-demo.md
  source/content/static-site-empty-upstream.md
Labels: quick fix

#9102 Fixing glossary TOC
  src/pages/glossary.js
Labels: Site: Site Structure

#9086 simplifying PHP redirects section
  source/content/guides/redirect/07-php.md
Labels: Type: Quick Fix

#9117 Create 2024-07-22-New-Relic-V2-API-Migration
  source/releasenotes/2024-07-23-new-relic-v2-api-migration.md
Labels: Type: release-notes

#9073 Update `shm_size` details for apcu.md
  source/content/apcu.md
Labels: Process: SME Wanted

#9053 Add alert about site naming restrictions
  source/content/guides/getstarted/06-addsite.md
Labels: Process: SME Wanted

#9118 [SITE-1553] WordPress 6.6.1
  source/releasenotes/2024-07-23-wordpress-6-6-1.md
Labels: Topic: WordPress, Type: release-notes

#9060 Workflow Logs GA: Release note and doc updates
  source/content/workflow-logs.md
  source/images/release-notes/2024/workflow-logs-key-features.jpg
  source/releasenotes/2024-07-24-workflow-logs.md
Labels: Process: Hold for Release, Type: release-notes

#9132 Update stale copy for CSM entitlement
  source/content/guides/professional-services/01-introduction.md
  source/content/guides/professional-services/03-onboarding.md
Labels: Type: Quick Fix

#9131 Copy edits: Support
  source/content/guides/support/01-scope.md
Labels: Type: Quick Fix

#9128 Revert "Revert "Workflow Logs GA: Release note and doc updates""
  source/content/workflow-logs.md
  source/images/release-notes/2024/workflow-logs-key-features.jpg
  source/releasenotes/2024-07-25-workflow-logs.md
Labels: Process: Hold for Release, Type: release-notes

#9134 Audit Site Downtime Playbook
  source/content/guides/disaster-recovery/01-introduction.md
  source/content/guides/disaster-recovery/02-planning-ahead.md
  source/content/guides/disaster-recovery/03-site-goes-down.md
  source/content/guides/disaster-recovery/04-incident-remediation.md
  source/images/dashboard/new-dashboard/platinum-support-site-dashboard.png
Labels: Type: Fix Content, Process: Needs SME

#9090 Secure Integration: document loopback IP usage
  source/content/guides/secure-development/02-secure-integration.md
Labels: topic: App Servers / Environments, Process: SME Wanted

#9115 disambiguating environment logs
  source/content/guides/logs-pantheon/01-introduction.md
  source/content/guides/logs-pantheon/02-access-logs.md
  source/content/guides/logs-pantheon/04-automate-log-downloads.md
  source/content/guides/logs-pantheon/05-nginx-access-logs.md
  source/content/guides/logs-pantheon/06-faq-logs.md
Labels: Type: Quick Fix, Process: SME Wanted
